#!/bin/bash

# a small bash script to check the battery remaining on the discharging mode

tt=$(bat | grep percentage | sed -e 's/[^0-9,]//g'| awk '{print int($1)}')

if [ $tt -le "8" ]; then
    echo "Hi, the Nexus 7 needs some alcohol" | mutt -s "Battery condition" wonderzqq@gmail.com
else
    export DISPLAY=:0 && /usr/bin/notify-send -i /home/beaver/Pictures/battery.png "Battery" "$tt percentage left"
fi
