#!/bin/bash

# a small bash script to say clock time

hour=$(date +"%H")

    if [ "$hour" = "01" ] || [ "$hour" = "13" ]; then
        hourZh='一'
    elif [ "$hour" = "02" ] || [ "$hour" = "14" ]; then
        hourZh='两'
    elif [ "$hour" = "03" ] || [ "$hour" = "15" ]; then
        hourZh='三'
    elif [ "$hour" = "04" ] || [ "$hour" = "16" ]; then
        hourZh='四'
    elif [ "$hour" = "05" ] || [ "$hour" = "17" ]; then
        hourZh='五'
    elif [ "$hour" = "06" ] || [ "$hour" = "18" ]; then
        hourZh='六'
    elif [ "$hour" = "07" ] || [ "$hour" = "19" ]; then
        hourZh='七'
    elif [ "$hour" = "08" ] || [ "$hour" = "20" ]; then
        hourZh='八'
    elif [ "$hour" = "09" ] || [ "$hour" = "21" ]; then
        hourZh='九'
    elif [ "$hour" = "10" ] || [ "$hour" = "22" ]; then
        hourZh='十'
    elif [ "$hour" = "11" ] || [ "$hour" = "23" ]; then
        hourZh='十一'
    elif [ "$hour" = "12" ] || [ "$hour" = "0" ]; then
        hourZh='十二'
    fi

/usr/bin/espeak -s 210 -v zh "$hourZh  点"

