#!/bin/bash

# a bash script for post-installation

rm -rf ~/examples.desktop

# Remove Unity desktop environment of UBUNTU
sudo apt-get autoremove --purge \
    unity unity-common unity-services unity-lens-\* unity-scope-\* unity-webapps-\* \
    gnome-control-center-unity hud libunity-core-6\* libunity-misc4 libunity-webapps\* \
    appmenu-gtk appmenu-gtk3 appmenu-qt\* overlay-scrollbar\* activity-log-manager-control-center \
    firefox-globalmenu firefox thunderbird-globalmenu thunderbird rhythmbox libufe-xidgetter0 \
    xul-ext-unity xul-ext-webaccounts webaccounts-extension-common xul-ext-websites-integration \
    gnome-control-center gnome-session software-center enscript \
    libzeitgeist-1.0-1 python-zeitgeist zeitgeist-core 

sudo apt-get autoremove -y

# A few libraries that are necessary for ubuntu
#sudo apt-get install -y \
#    gir1.2-unity-5.0 libunity-common libunity-protocol-private0 libunity9 unity-asset-pool unity-greeter

sudo rm /usr/lib/thunderbird-addons/extensions/messagingmenu@mozilla.com.xpi ~/.local/share/unity-webapps


# add repositories
sudo add-apt-repository -y "deb http://dl.google.com/linux/chrome/deb/ stable main"
sudo add-apt-repository -y ppa:synapse-core/ppa
sudo add-apt-repository -y ppa:ubuntu-mate-dev/ppa
sudo add-apt-repository -y ppa:ubuntu-mate-dev/trusty-mate

# basic update
sudo apt-get -y update
sudo apt-get -y upgrade

# install software
sudo apt-get -y install --no-install-recommends ubuntu-mate-core ubuntu-mate-desktop

sudo apt-get -y install \
    wget vim gcc g++ gfortran fort77 f2c cmake make \
    gnuplot octave git texlive-full mutt mplayer mc apvlv dia \
    openssh-client openssh-server mc synaptic nfs-common bikeshed \
    liblapack3 liblapack-dev libblas3 libhdf5-dev synapse zsh \
    cowsay fortune cpufrequtils curl dropbox build-essential python3-pip \
    google-chrome-stable virtualbox virtualbox-guest-additions-iso ubuntu-restricted-extras \
    libncurses5-dev vim-latexsuite dos2unix 


# Progress viewer
git clone https://github.com/Xfennec/progress.git

cd progress
make
sudo make install
cd .. && rm -rf progress


# youtube-dl
wget https://yt-dl.org/downloads/latest/youtube-dl -O /usr/local/bin/youtube-dl
chmod a+rx /usr/local/bin/youtube-dl


# sundials
cd ~/Downloads
wget http://computation.llnl.gov/projects/sundials/download/sundials-2.6.2.tar.gz  
tar -xvf sundials-2.6.2.tar.gz
mkdir sundialsbuild && cd sundialsbuild
cmake -DCMAKE_INSTALL_PREFIX="/usr/local/sundials" -DEXAMPLES_ENABLE=OFF -DOPENMP_ENABLE=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_FLAGS=-fPIC ../sundials-2.6.2

make
make install

cd .. && rm -rf sundialsbuild


# nmap-7.0.0
wget https://nmap.org/dist/nmap-7.00.tar.bz2
bzip2 -cd nmap-7.00.tar.bz2 | tar xvf -
cd nmap-7.00

./configure
make
sudo make install

cd .. && rm -rf nmap-7.00


# CADET
git clone https://github.com/modsim/CADET.git
mkdir buildCadet && cd buildCadet
export SUNDIALS_ROOT=/usr/local/sundials
##export HDF5_ROOT=/usr/local/hdf5
##export MATLAB_ROOT=/usr/local/MATLAB/R2014a
cmake -DCMAKE_INSTALL_PREFIX="/usr/local/cadet" ../CADET*/
make
make install
cd ~


## ubuntu flat theme
wget https://launchpad.net/~ravefinity-project/+archive/ubuntu/ppa/+files/vibrancy-colors_2.7~xenial~Noobslab.com_all.deb

sudo dpkg -i vibrancy*

wget https://launchpad.net/~ravefinity-project/+archive/ubuntu/ppa/+files/ambiance-flat-colors_14.04.2~trusty~NoobsLab.com_all.deb
wget https://launchpad.net/~ravefinity-project/+archive/ubuntu/ppa/+files/radiance-flat-colors_14.04.2~trusty~NoobsLab.com_all.deb

sudo dpkg -i ambiance*
sudo dpkg -i radiance*

# oh-my-zsh
sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"

# Powerline
sudo pip3 install git+git://github.com/Lokaltog/powerline

wget https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf
wget https://github.com/powerline/powerline/raw/develop/font/10-powerline-symbols.conf

mkdir -p ~/.fonts/ && mv PowerlineSymbols.otf ~/.fonts/
fc-cache -vf ~/.fonts
fc-cache -vf /usr/share/fonts
mkdir -p ~/.config/fontconfig/conf.d/ && mv 10-powerline-symbols.conf ~/.config/fontconfig/conf.d/


# Purge repository
sudo add-apt-repository --remove "deb http://dl.google.com/linux/chrome/deb/ stable main"
sudo add-apt-repository --remove ppa:synapse-core/ppa
sudo add-apt-repository --remove ppa:ubuntu-mate-dev/ppa
sudo add-apt-repository --remove ppa:ubuntu-mate-dev/trusty-mate


# Chinese font installation LaTex
sudo ln -s /usr/share/texlive/texmf-dist/tex/latex/ctex/fontset/ctex-xecjk-winfonts.def /etc/fonts/conf.d/09-texlive.conf

cd /usr/share/fonts
sudo mkdir winfonts && cd winfonts
sudo mv ~/Downloads/*.ttf .
sudo chmod 644 *
sudo chown root:root *.ttf
sudo mkfontscale
sudo mkfontdir
sudo fc-cache -fsv

cd /usr/share/texlive/texmf-dist/tex/latex/ctex/fontset/

sed 's|\%\\setCJK|\\setCJK|g' ctex-xecjk-winfonts.def | sudo tee ctex-xecjk-winfonts.def
sed 's|\%\\newcommand|\\newcommand|g' ctex-xecjk-winfonts.def | sudo tee ctex-xecjk-winfonts.def

sed 's|SIMKAI.TTF|KaiTi|g' ctex-xecjk-winfonts.def | sudo tee ctex-xecjk-winfonts.def
sed 's|SIMFANG.TTF|FangSong|g' ctex-xecjk-winfonts.def | sudo tee ctex-xecjk-winfonts.def

cd ~


# vim configuration
tar -xvf vim.tar.gz ~/


# reboot
echo "========================================"
echo ":) Everything goes well. Time for reboot"
echo "========================================"
echo ""
